### PR TITLE
use url_for to generate URLs

### PR DESCRIPTION
**Pull request by fvanderbiest**
so that final slashes in paths are correctly handled...

### CODE REVIEW

**Comment by fvanderbiest** [comment]
built with docker tag 20170726140000

**Comment by fvanderbiest** [comment]
Hmm, works locally because the app is available from / but **not when the SP maps it onto /foncier**, eg in targets-mapping.properties:
```
geoserver=http://geoserver-lb:80/geoserver/
foncier=http://app.georchestra-foncier:5000/
```
.. this is because url_for loads https://dev.geopicardie.fr/static/styles.css rather than https://dev.geopicardie.fr/foncier/static/styles.css

At least the behavior is now consistent, may I load https://dev.geopicardie.fr/foncier or https://dev.geopicardie.fr/foncier/ ;-)

**Comment by fvanderbiest** [comment]
http://flask.pocoo.org/docs/0.11/blueprints/ to the rescue ...

**Review by Vampouille — APPROVED** [review]

**Comment by fvanderbiest** [comment]
new docker tag is 20170726155600

**Comment by fvanderbiest** [comment]
App crashes when it receives an incoming request from the SP, without any log ...

**Comment by fvanderbiest** [comment]
> App crashes when it receives an incoming request from the SP, without any log ...

I simply forgot that we had a healthcheck on / !

**Pull request merged**
